### ISSUE TITLE
Option: Automatically push new branch to remote

### ISSUE THREAD

**Issue by BuriedStPatrick** [BuriedStPatrick/pwsh#1]
When creating a new branch, provide option to automatically push the branch to the remote repository.

It should be an option in the Git module config in `pwsh.yaml`.
Default should be 'never' so we don't change previous behavior.

* Always: Always push new branches to the remote
* Interactive: Prompt the user to push the branch to the remote. If yes, push.
* Never: Completely disable this feature. User will have to push manually.

```yaml
modules:
  Git:
    config:
      pushNewBranches: always | interactive | never
```
